services:
  - type: web
    name: workflow-wizard
    env: node
    region: singapore
    plan: free
    buildCommand: |
      npm install --legacy-peer-deps
      npm run build:client
      npm run build:server
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 3000
    healthCheckPath: /health
    autoDeploy: true
